pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [adamgfraser]
      label:
        add: [dependency-update]
  - name: merge Scala Steward's PRs
    conditions:
      - base=master
      - author=scala-steward
      - "body~=(labels: library-update, semver-minor)|(labels: library-update, semver-patch)|(labels: sbt-plugin-update, semver-minor)|(labels: sbt-plugin-update, semver-patch)|(labels: scalafix-rule-update, semver-minor)|(labels: scalafix-rule-update, semver-patch)|(labels: test-library-update, semver-minor)|(labels: test-library-update, semver-patch)"
      - "status-success=license/cla"
      - "status-success=lint"
      - "status-success=test (adopt@1.8, 2.11.12, JVM)"
      - "status-success=test (adopt@1.8, 2.11.12, JS)"
      - "status-success=test (adopt@1.8, 2.11.12, Native)"
      - "status-success=test (adopt@1.8, 2.12.13, JVM)"
      - "status-success=test (adopt@1.8, 2.12.13, JS)"
      - "status-success=test (adopt@1.8, 2.12.13, Native)"
      - "status-success=test (adopt@1.8, 2.13.5, JVM)"
      - "status-success=test (adopt@1.8, 2.13.5, JS)"
      - "status-success=test (adopt@1.8, 2.13.5, Native)"
      - "status-success=test (adopt@1.8, 3.0.0-RC1, JVM)"
      - "status-success=test (adopt@1.8, 3.0.0-RC1, JS)"
      - "status-success=test (adopt@1.8, 3.0.0-RC1, Native)"
      - "status-success=test (adopt@1.11, 2.11.12, JVM)"
      - "status-success=test (adopt@1.11, 2.11.12, JS)"
      - "status-success=test (adopt@1.11, 2.11.12, Native)"
      - "status-success=test (adopt@1.11, 2.12.13, JVM)"
      - "status-success=test (adopt@1.11, 2.12.13, JS)"
      - "status-success=test (adopt@1.11, 2.12.13, Native)"
      - "status-success=test (adopt@1.11, 2.13.5, JVM)"
      - "status-success=test (adopt@1.11, 2.13.5, JS)"
      - "status-success=test (adopt@1.11, 2.13.5, Native)"
      - "status-success=test (adopt@1.11, 3.0.0-RC1, JVM)"
      - "status-success=test (adopt@1.11, 3.0.0-RC1, JS)"
      - "status-success=test (adopt@1.11, 3.0.0-RC1, Native)"
    actions:
      merge:
        method: squash
