#!/usr/bin/env bash

packages=(
  "@zio.dev/caliban-deriving"
  "@zio.dev/interop-monix"
  "@zio.dev/izumi-reflect"
  "@zio.dev/zio-actors"
  "@zio.dev/zio-akka-cluster"
  "@zio.dev/zio-aws"
  "@zio.dev/zio-cache"
  "@zio.dev/zio-cli"
  "@zio.dev/zio-config"
  "@zio.dev/zio-connect"
  "@zio.dev/zio-constraintless"
  "@zio.dev/zio-deriving"
  "@zio.dev/zio-direct"
  "@zio.dev/zio-dynamodb"
  "@zio.dev/zio-flow"
  "@zio.dev/zio-ftp"
  "@zio.dev/zio-http"
  "@zio.dev/zio-insight"
  "@zio.dev/zio-interop-guava"
  "@zio.dev/zio-interop-reactivestreams"
  "@zio.dev/zio-interop-scalaz"
  "@zio.dev/zio-interop-twitter"
  "@zio.dev/zio-jdbc"
  "@zio.dev/zio-json"
  "@zio.dev/zio-kafka"
  "@zio.dev/zio-lambda"
  "@zio.dev/zio-logging"
  "@zio.dev/zio-memberlist"
  "@zio.dev/zio-meta"
  "@zio.dev/zio-metrics-connectors"
  "@zio.dev/zio-mock"
  "@zio.dev/zio-nio"
  "@zio.dev/zio-optics"
  "@zio.dev/zio-parser"
  "@zio.dev/zio-prelude"
  "@zio.dev/zio-process"
  "@zio.dev/zio-profiling"
  "@zio.dev/zio-query"
  "@zio.dev/zio-quill"
  "@zio.dev/zio-redis"
  "@zio.dev/zio-rocksdb"
  "@zio.dev/zio-s3"
  "@zio.dev/zio-sbt"
  "@zio.dev/zio-schema"
  "@zio.dev/zio-sql"
  "@zio.dev/zio-sqs"
  "@zio.dev/zio-telemetry"
  "@zio.dev/zio-webhooks"
  "@zio.dev/zio2-interop-cats2"
  # this seems to be deleted and no longer exists
  # "@zio.dev/zio2-interop-cats3"
)

# Construct the package add command by joining the packages with a space
cmd="yarn add ${packages[@]}"

# Run the command
eval $cmd