name: Auto-approve bot dependency PRs

on: pull_request_target

permissions:
  pull-requests: write

jobs:
  auto-approve-bot-prs:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'app/zio-scala-steward'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Approve PR
        run: gh pr review --approve ${{ github.event.number }}
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
